'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace PopupControlContentUpdateOnCallback


	''' <summary>
	''' _Default class.
	''' </summary>
	''' <remarks>
	''' Auto-generated class.
	''' </remarks>
	Partial Public Class _Default

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' btnShowContent1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnShowContent1 As Global.DevExpress.Web.ASPxButton

		''' <summary>
		''' btnShowContent2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnShowContent2 As Global.DevExpress.Web.ASPxButton

		''' <summary>
		''' btnShowContent3 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnShowContent3 As Global.DevExpress.Web.ASPxButton

		''' <summary>
		''' pcPopup control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected pcPopup As Global.DevExpress.Web.ASPxPopupControl

		''' <summary>
		''' pgcPageControl control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected pgcPageControl As Global.DevExpress.Web.ASPxPageControl
	End Class
End Namespace
